### ISSUE TITLE
Adopt a standard license

### ISSUE THREAD

**Issue by saildata** [bryantbhowell/tableau_tools#1]
Great job on this project! The only concern I have is the very brief mention of rights in the README:
`
This is free and available for anyone to use and modify.` 

If you are comfortable with doing so, would you mind adding a standard license to the project? (MIT, GPL, etc..) I'm not a lawyer, so this is just something I noticed looking at the project overview.

In the past, I've found the following two sites helpful in understanding the general differences between the various licenses:
[https://tldrlegal.com/](tldr legal)
[http://choosealicense.com/](tldr legal)

Cheers - 
Stephen

**Comment by mcoles** [comment]
MIT would be preferred for consistency with the other projects in https://github.com/tableau (see James Baker's internal wiki page on contributing to public Tableau projects)

**Comment by saildata** [comment]
@mcoles Going through my open/old issues - is this safe to close?

Also, thank you for posting the link to the other projects! :trophy:

**Comment by mcoles** [comment]
@bryantbhowell should make that call. he can do what he likes with this issue, I suppose--I'm merely suggesting that if a standard license is adopted, the MIT license is a good candidate since that's what our own internal guidelines suggest.

**Comment by bryanthowell-tableau** [comment]
The library is licensed with the MIT licensing verbiage now (and has been for a least a few releases)
