### ISSUE TITLE
TableauDocument.save_file(filename) Not allowing saving

### ISSUE THREAD

**Issue by daVinciCEB** [bryantbhowell/tableau_tools#18]
I am testing out the functionality of the tableau_tools.tableau_documents package, looking into creating tableau datasources in code. Unfortunately, before I can even start creating datasources, I want to make sure I can create and save a new file, which I currently cannot do.

My function:
```python
def test_tableau_tools_library():
    LOGGER = Logger("log.log")
    new_tableau_file = TableauFile("test.tds", logger_obj=LOGGER, create_new=True, ds_version=u'10')
    print(new_tableau_file.file_type)
    new_tableau_document = new_tableau_file.tableau_document
    print(new_tableau_document.document_type)
    new_tableau_document.save_file(u'test')
```

While attempting to run this function, I receive the following error:
```
Traceback (most recent call last):
  File "tableau_datasource_creator/tableau_datasource_creator.py", line 17, in <module>
    test_tableau_tools_library()
  File "tableau_datasource_creator/tableau_datasource_creator.py", line 14, in test_tableau_tools_library
    new_tableau_document.save_file(u'test', save_to_directory="testing")
  File "C:\Users\COBY~1.BEN\Desktop\env\lib\site-packages\tableau_tools\tableau_documents\tableau_datasource.py", line 315, in save_file
    lh.write(self.get_datasource_xml())
  File "C:\Users\COBY~1.BEN\Desktop\env\lib\codecs.py", line 718, in write
    return self.writer.write(data)
  File "C:\Users\COBY~1.BEN\Desktop\env\lib\codecs.py", line 376, in write
    data, consumed = self.encode(object, self.errors)
TypeError: utf_8_encode() argument 1 must be str, not bytes
```

**Comment by daVinciCEB** [comment]
It looks like the xmlstring that is being returned by get_datasource_xml() is returning bytes, instead of a string, which is necessary for the file to save.

**Comment by bryanthowell-tableau** [comment]
Hi - wanted to check a few things with you, as I'm not seeing this issue in the current version using Python 2.7.14 on my test machine. I've run your exact code and it is working.

Can you tell me (1) Version of Python (2) Operating System (3) Version of tableau_tools you are using? 

The etree.tostring() method should be returning a string every time, so I don't know why there would need to be another casting.

**Comment by daVinciCEB** [comment]
Python Version: 3.6.4
OS: Windows 10
tableau_tools Version: Latest

I'm almost certain that this is a compatibility issue between Python 2 and Python 3. When I went and checked the types that were being returned, it shows that `xmlstring` is actually a bytes instance and not a string instance. That's why I added the extra cast to return it as a string.

**Comment by daVinciCEB** [comment]
The Tableau Datasource is the only file I had used so far, so I only changed that one, but it could be that `etree.tostring()` is returning bytes everywhere, so wherever you have used it might need to be changed

**Comment by daVinciCEB** [comment]
Actually, after further investigation, looks like `etree.tostring()` returns a [byte string unless otherwise specified](https://docs.python.org/3/library/xml.etree.elementtree.html#xml.etree.ElementTree.tostring).

I'll check this in my current code and see if using `encoding="unicode"` works, if it does I'll adjust my PR accordingly.

**Comment by richardhanson** [comment]
Hi guys. Ran into the same issue with Python 3.7. Adding encoding='unicode' fixed the issue for me. @bryantbhowell do you have time to review the PR and test if it works with Python 2.7? I have tested in Python 3.7 and it works there as well

**Comment by richardhanson** [comment]
My PR to fix the issues raised in #41 includes a @daVinciCEB 's fix for this as well as my company needed it.

**Comment by bryanthowell-tableau** [comment]
Thanks for doing the work on this and my apologies that it has hung out there for so long. Let me see if there is way to fix this that maintains a single source tree

**Comment by bryanthowell-tableau** [comment]
Added a check for if type 'bytes' to convert to a unicode string. That should only be ever activated in Python 3.X . I've checked into the code which should go into the 4.6.2 release. Will notify when that release is available.

**Comment by bryanthowell-tableau** [comment]
Version 4.6.2 is now released with a fix for this issue. Please reopen if the issue persists.

**Comment by rtimothyweeks** [comment]
I encountered the same _TypeError: utf_8_encode() argument 1 must be str, not bytes_ error on new_tableau_document.save_file(u'test') and making the changes to tableau_datasource.py represented in #42 allowed my script to run.

Python Version: 3.7.0
OS: Windows 10
tableau_tools Version: Latest (4.6.5)
