### ISSUE TITLE
Support SSL certificate options for tableau_http.py

### ISSUE THREAD

**Issue by mcoles** [bryantbhowell/tableau_tools#2]
Right now it seems as though the TableauHTTP class is agnostic as to whether it receives a URL that uses HTTPS as a protocol vs. unencrypted HTTP. HTTPS is clearly preferred for everything, but we've had issues getting Python running on Windows to properly verify internal certs that we've generated. And some certs may throw verification errors, which we don't care about immediately, but still want to encrypt our traffic.

So, it'd be great if we could support verify / don't verify and cafile / capath options in this class, all as optional parameters.

Thanks!

**Comment by bryanthowell-tableau** [comment]
Closing from the dead -- in 5.X, TableauHTTP uses standard Python requests library and you can just access the .session property and drop in any custom requests.Session object you need if necessary.

**Comment by rlmagidson** [comment]
Hi there - I believe this thread is answering the question I have but am not 100% sure... I'm receiving an SSL: CERTIFICATE_VERIFY_FAILED error when trying to connect to our Tableau server. Can you help me understand how to install a local certificate or ignore the error? Many thanks! - rlm

**Comment by bryanthowell-tableau** [comment]
I thought this was documented by it is not in the README -- for any of the API objects (TableauServerRest32 etc.), once you've create the object you can set the 'verify_ssl_cert' property to False to ignore the warnings for self-signed.

Example: 
      t = TableauServerRest32(server=server, username=admin_username, password=admin_password)
        # Using self-signed AWS certs, so turn off cert verification
        t.verify_ssl_cert = False
        t.signin()

This maps directly to the property in the Python requests library, so you can also specify any other value you would use based on the Requests documentation.

**Comment by rlmagidson** [comment]
Awesome. Thank you for that quick reply and I apologize if you had to repeat yourself. 

Be well
- rlm
