### ISSUE TITLE
update in pypi repo

### ISSUE THREAD

**Issue by ausiddiqui** [bryantbhowell/tableau_tools#21]
Would it be possible to push changes into PyPi repo? The latest version on that is 4.3.16 from 2/22. Thanks!

**Comment by bryanthowell-tableau** [comment]
I just pushed the 4.4.0 release up to PyPi. There were a lot of changes and additions which meant there was more time than usual between additions and a release. The releases are tracked in GitHub as well, while the main branch does get updated as I'm working locally.
