### ISSUE TITLE
tableau_parameter.py failing when getting datasource characteristics

### ISSUE THREAD

**Issue by tone711** [bryantbhowell/tableau_tools#24]
I have a Parameters data source which has copied parameters. Some of them have been copied more than once. In that case, Tableau appends '(copy 2)' or '(copy #)' depending on how many times it's been copied. The if internal_name.find condition should account for that possibility. Thank you!

Starting at line 43:
```
# Parameters are all given internal name [Parameter #], unless they are copies where they
# end with (copy) h/t Jeff James for discovering
                if internal_name.find(u'(copy)') == -1:
```

**Comment by bryanthowell-tableau** [comment]
Hi tone711 -- There should be a patch in 4.5.0 that fixes this. Can you let me know if it is working now?
