### ISSUE TITLE
can we create a tableau extract without using tableau but by using tableau_tools?

### ISSUE THREAD

**Issue by qxlsz** [bryantbhowell/tableau_tools#25]
can we create a tableau extract without using tableau but by using tableau_tools?

**Comment by bryanthowell-tableau** [comment]
tableau_tools has a functionality to convert a datasource that is a Live Connection into one with an Extract, but it is actually using the [Tableau Extract API ](https://onlinehelp.tableau.com/current/api/extract_api/en-us/help.htm) to perform the Extract creation. The Extract API does not require a Tableau Desktop or Server and can be installed on any machine. You can use it directly to create an Extract from any source, or use the tableau_tools integration to create a TDSX that has both the live connection description and the necessary extract piece.
