### ISSUE TITLE
Change parameter in published workbook?

### ISSUE THREAD

**Issue by michigalli** [bryantbhowell/tableau_tools#26]
Hello Bryan,
is it possible to edit the XML structure of a published workbook, for example by published_workbook_object?

I need to find a way to edit parameters in an wb after publishing.

Best regards,
Michael

**Comment by bryanthowell-tableau** [comment]
You can download the published workbook, change the XML, then republish over the existing data source and that should update things. 

Are you just looking to change the default parameter values, or the actual structures of them?

Parameter values can also be set at report load time via the JS API constructor, or URL Parameters, or also using the JS API after load time.
