### ISSUE TITLE
Python 3.0 support

### ISSUE THREAD

**Issue by blackhat06** [bryantbhowell/tableau_tools#28]
Hi team, 

are we supporting Python 3.0 for this package.

Thanks,
Vick

**Comment by bryanthowell-tableau** [comment]
Yes, it is written with Python2to3 in mind, so if you install via pip on a version of Python 3, everything should be upgraded automatically to Python 3 code. Please file an issue if you find anything that does not work. The functionality that ties in to the Tableau Extract API will not work currently on Python 3 but I believe there are updates coming to provide compatibility in that package at some point in the near future.
