### ISSUE TITLE
self.__publish = True remains after send_publish_request or send_append_request

### ISSUE THREAD

**Issue by awithey-sedex** [bryantbhowell/tableau_tools#29]
If you publish content, any subsequent (non-publish) update fails.

The send_publish_request and send_append_request methods call set_publish_content(content, boundary_string) and that sets__publish = True
However, in their "cleanup" code, when they call self._request_obj.set_publish_content(None, None) ,
sets__publish remains True.

see:
https://github.com/bryantbhowell/tableau_tools/blob/f64a04a8b5d79807bd12a03459508b377462c92b/tableau_rest_api/tableau_rest_api_connection.py#L407

Subsequent calls to update have the wrong ContentType set.
see: https://github.com/bryantbhowell/tableau_tools/blob/f64a04a8b5d79807bd12a03459508b377462c92b/tableau_rest_api/rest_xml_request.py#L138

Thanks,

Andrew

**Comment by bryanthowell-tableau** [comment]
Andrew, 
Thank you for finding this, the fix will be in the 4.6.0 release sometime soon. I've already committed them up to see in GitHub.
