### ISSUE TITLE
TableauSDK and tableau_rest_api

### ISSUE THREAD

**Issue by scenting** [bryantbhowell/tableau_tools#3]
Hi,

Previous project [tableau_rest_api](https://github.com/bryantbhowell/tableau_rest_api) did not require the TableauSDK dependency, which is not on PyPI and can be a pain to install inside docker images.

Is there a way of using tableautools.tableau_rest_api without requiring this extra dependency?

Thanks,

**Comment by bryantbhowell** [comment]
I made a change in 3.1.0 so that the include is optional and only happens if you try to modify the datasource structure when there is an included TDE. It is necessary in those cases however. Let me know if that is not working.

**Comment by scenting** [comment]
Thanks!
