### ISSUE TITLE
query_datasource with a name AND a project_id returns the wrong datasource

### ISSUE THREAD

**Issue by awithey-sedex** [bryantbhowell/tableau_tools#38]
If you call query_datasource with a name AND a project id, the method returns the first datasource in that project, no matter what the name.

This appears to be due to the method getting _all_ datasources, then doing a findall by name, ignoring that result and doing a findall by project id on the full list and returning the first datasource!

PS: If your server has a lot of datasources, this method takes a very long time to return due to the REST call returning all datasources first. Can you update it to use name:eq: filter and then filter the result by project id (if required)?

Thanks,

Andrew

**Comment by bryanthowell-tableau** [comment]
Hi Andrew,
I've gone through and made updates to fix the logic and use the name filtering on 10.3 and later for workbooks (10.4 and later for datasources) to vastly speed things up. Thank you for finding these issues and suggesting the performance improvements.

Fix will be in the next release
