### ISSUE TITLE
Support for REST API version 2.3 and Tableau Server 10

### ISSUE THREAD

**Issue by champ** [bryantbhowell/tableau_tools#4]
Tableau has released version 10 of Tableau Server and [version 2.3 of the REST API](https://onlinehelp.tableau.com/current/api/rest_api/en-us/help.htm#REST/rest_api_whats_new.htm%3FTocPath%3D_____2). Although there doesn't seem to be any evident backward incompabilities, the new version adds a whole lot of useful features.

**Comment by bryantbhowell** [comment]
The 3.1.0 release brings in compatibility and implements most of the features. Still need to work on the revisioning features and using the quick lookup methods. Expect that in subsequent releases
