### ISSUE TITLE
Option to Include/Exclude Extract When Downloading Content

### ISSUE THREAD

**Issue by tableaukun** [bryantbhowell/tableau_tools#40]
When downloading a datasource/workbook, Tableau provides a flag option to [include or exclude](https://onlinehelp.tableau.com/v10.5/api/rest_api/en-us/help.htm#REST/rest_api_ref.htm#Download_Datasource%3FTocPath%3DAPI%2520Reference%7C_____41) the underlying extract. 

Is it possible to add this as a filter or additional function? Thanks!

**Comment by bryanthowell-tableau** [comment]
Implemented in version 4.6.3 which is now available
