### ISSUE TITLE
Creating a Datasource from Scratch - Type Error for ds_string

### ISSUE THREAD

**Issue by tableaukun** [bryantbhowell/tableau_tools#45]
For the new version 4.6.3 (and 4.6.2), there now appears to be a Type error on line 390 in the tableau_datasource.py file:
`if type(ds_string, u'bytes'):` throws an error: `TypeError: type() takes 1 or 3 arguments`
This appears to be a new addition. Will ds_string ever be a byte?

**Comment by bryanthowell-tableau** [comment]
That should have been an isinstance() check -- in Python 3, that should be a bytes (the equivalent of a Python 2 string), and then it will get converted to a real unicode Python 3 string. I just uploaded 4.6.4 with the fix -- can you test and let me know if it works?

**Comment by tableaukun** [comment]
That worked. Thanks!
