### ISSUE TITLE
AWS Athena needs both "dbname" and "schema" fields in TableauConnection

### ISSUE THREAD

**Issue by nightrise** [bryantbhowell/tableau_tools#46]
Tableau connection currently assumes "schema" to be an alias for "dbname", whereas Athena uses both these fields in the xml, and in fact expects them to be different.

This is problematic when replicating publishing connections, as doing a conn.schema = u'whatever' actually modifies the "dbname" field in the xml, rather than the "schema" field, as would be proper.

**Comment by weallwegot** [comment]
@nightrise yea running into issues with same root cause. Can't truly identify differences within the datasources as 

`.dbname` and `.schema` both return `AwsDataCatalog`


did this prove to make the whole repository unusable for use with modifying datasources for Athena connections?

**Comment by bryanthowell-tableau** [comment]
I know it's been a long time, but this should be corrected in version 5.0.3 which will be out shortly. Now .schema actually sets and gets from schema unless there is no schema property, then it will default back to dbname (to try and help make these changes generic across data sources when at all possible).
