### ISSUE TITLE
TableauRestApiConnection32 declared in tableau_rest_api_connection_33.py

### ISSUE THREAD

**Issue by davlion** [bryantbhowell/tableau_tools#62]
the file tableau_rest_api_connection_33.py declares a class named TableauRestApiConnection32.   
Should this class actually be named TableauRestApiConnection33?

**Comment by bryanthowell-tableau** [comment]
Yes, that was definitely just a typo. This should be corrected in both the final 4.9. series release and in the new 5.X releases.
