### ISSUE TITLE
Tabcmd export user impersonation

### ISSUE THREAD

**Issue by mkosla** [bryantbhowell/tableau_tools#65]
I believe the Tabcmd.create_export command's User Impersonation does not work on Python 3.4+. Tracing the error led me to tableau_http.py which calls request.add_data(). The add_data function was removed from urllib.

**Comment by bryanthowell-tableau** [comment]
This should be fixed in version 5.0.3+. I switched TableauHTTP to use requests instead of the old urllib calls.

**Comment by bryanthowell-tableau** [comment]
Actually, I had to remove out that User Impersonation thing, but it shouldn't be an issue because there are now REST API methods for all of the export types it was used for. There were some security questions raised about the way it worked previously.
